
name: Verify
on: [push]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: profilehunt_test
          POSTGRES_PASSWORD: "postgres"
        ports: ["5432:5432"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.15.0
      - name: Find yarn cache location
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: JS package cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install packages
        run: |
          yarn install --pure-lockfile

      - name: Setup test database
        env:
          RAILS_ENV: test
          DATABASE_POSTGRES_HOST: localhost
          DATABASE_POSTGRES_USERNAME: "postgres"
          DATABASE_POSTGRES_PASSWORD: "postgres"
        run: |
          bin/rails db:create
          bin/rails db:migrate
      - name: Run tests
        env:
          RAILS_ENV: test
          DATABASE_POSTGRES_HOST: localhost
          DATABASE_POSTGRES_USERNAME: "postgres"
          DATABASE_POSTGRES_PASSWORD: "postgres"
        run: bundle exec rspec
